global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus_scrape"
    metrics_path: "/metrics"
    static_configs:
      # domain to access host
      - targets: ["host.docker.internal:2223"]
